### PR TITLE
build-arg: allow setting additional omego args

### PR DESCRIPTION
**Pull request by joshmoore**
```
usage: docker build -t test . \
    --build-arg OMERO_VERSION=OMERO-build
    --build-arg OMEGO_ADDITIONAL_ARGS=--ci=http://devspace/
```

### CODE REVIEW

**Comment by joshmoore** [comment]
Could possibly help with gh-4

**Comment by manics** [comment]
Does this work? I thought devspace defaults to https with a self-signed cert?

**Comment by joshmoore** [comment]
It worked for me. Also have devspace doing the same regularly now.

**Comment by joshmoore** [comment]
See @kennethgillen's comment under https://github.com/openmicroscopy/omero-web-docker/pull/16#issuecomment-351410892

**Comment by jburel** [comment]
I have tried using the IP of the devspace created in openstack (both http and https)
It failed with the following 

```
TASK [openmicroscopy.omero-server : omero server | install omero] **************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/opt/omero/omego/bin/omego", "install", "--release", "OMERO-build", "--sym", "OMERO.server", "--ice", "3.6", "--no-start", "--ignoreconfig", "-qq", "--ci=http://10.0.51.143", "--dbhost", "localhost", "--dbuser", 
```
i tried to specify the port, no luck

**Comment by kennethgillen** [comment]
Using same ci-server as for omero-web-docker:

`  docker build -t omero-server-docker-test .  --build-arg OMERO_VERSION=OMERO-build --build-arg OMEGO_ADDITIONAL_ARGS=--ci=https://ci-server`

Built version matches next-ci as of https://ci-server/job/OMERO-server/31/console

```
LS27172:omero-server-docker kenny$ docker exec -it server-test bash
bash-4.2$ /opt/omero/server/OMERO.server/bin/omero admin diagnostics | grep 5
WARNING:omero.util.UpgradeCheck:UPGRADE AVAILABLE:Please upgrade to 5.4.1. See http://downloads.openmicroscopy.org/latest/omero for the latest version.
OMERO Diagnostics (admin) 5.4.0-128-6b28ede-ice36-b31
```

**Comment by joshmoore** [comment]
@jburel : can you show the command you ran as well as the output of `docker ps` on your host? (and/or add my key)

**Comment by jburel** [comment]
@joshmoore sorry for the confusion I  have just realised  that in the command I ran I had a typo in the omero version
I have tested both http and https and it works

**Comment by joshmoore** [comment]
see https://github.com/openmicroscopy/omero-web-docker/pull/16#issuecomment-353102533

**Pull request merged**
